### ISSUE TITLE
Publish compiled binaries to `Releases`

### ISSUE THREAD

**Issue by Korb** [gavrilovegor519/fidoip-ng#1]
Not all users are programmers (most are not), have software installed to compile an application from source code, and know how to use this software. However, Github provides a very convenient way for users to subscribe to new releases, and it would be convenient to download new binary packages right [there](https://github.com/gavrilovegor519/fidoip-ng/releases), rather than looking for them elsewhere.

**Comment by oldzoomer-ru** [comment]
I'm now build binary packages for convenience, but some config scripts located in source tree (this is architecture feature of upstream project, sorry). Therefore, you will still have to download the source codes themselves.
